#cloud-config
package_update: true
package_upgrade: true

packages:
  - python3-pip
  - git

runcmd:
  - cd /home/azureuser
  - git clone https://github.com/replit/azuremetadatafetcher.git
  - cd azuremetadatafetcher
  - pip3 install -r requirements.txt

write_files:
  - path: /etc/systemd/system/azure-metadata-fetcher.service
    content: |
      [Unit]
      Description=Azure Metadata Fetcher
      After=network.target

      [Service]
      User=azureuser
      WorkingDirectory=/home/azureuser/azuremetadatafetcher
      ExecStart=/usr/bin/python3 /home/azureuser/azuremetadatafetcher/main.py
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - systemctl daemon-reload
  - systemctl enable azure-metadata-fetcher.service
  - systemctl start azure-metadata-fetcher.service
